name: bulk-build

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/pkgsrc-ohos/ci-runner:latest
      volumes:
        - /opt/node24:/__e/node24:rw,rshared
    steps:
      - name: Setup Node.js for actions
        run: |
          curl -fsSLO https://github.com/hqzing/ohos-node/releases/download/v24.2.0/node-v24.2.0-openharmony-arm64.tar.gz
          mkdir /__e/node24/bin
          tar -zxf node-v24.2.0-openharmony-arm64.tar.gz -C /opt
          ln -s /opt/node-v24.2.0-openharmony-arm64/bin/node /__e/node24/bin/node
          rm node-v24.2.0-openharmony-arm64.tar.gz

      - name: Checkout Source
        uses: actions/checkout@v5

      - name: Bulk Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./bulk-build.sh
